#!/bin/sh

go mod tidy

UPDATES=$(awk '$1 !~ /^$|^(module|go|require|\))$/ {print $1}' go.mod \
  | xargs go list -u -m)

COMMANDS=$(echo "$UPDATES" | awk '$3 != "" {
    newver = substr($3, 2, length($3)-2);
    printf "go get %s@%s\n", $1, newver;
  }' -)

echo "$UPDATES"

IFS='
'
for cmd in $COMMANDS; do
  echo ""
  echo "Running: $cmd"
  OUT=$(eval "$cmd" 2>&1)
  if [ -n "$OUT" ]; then echo "$OUT"; fi
done

# The downgrade picks 1.65.0-dev which I don't like because it says -dev
go get google.golang.org/grpc@v1.64.1

go get go@1.20 toolchain@none
go mod tidy
