name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.17'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Test quickstart
      shell: bash
      run: |
        (go build -v ./... && (mkdir -p quicktest && mv daemon quicktest/)) || exit 1
        cd quicktest && (echo "password" | ./daemon spawn 2&>1 > logs.txt &; sleep 5; killall daemon)
        if [ -n "$(grep 'Token received' quicktest/logs.txt)" ]; then exit 1; fi
        if [ -n "$(grep 'Obtained TLS lease' quicktest/logs.txt)" ]; then exit 1; fi
        if [ -n "$(grep 'https://127.0.0.1:8080/daemon/' quicktest/logs.txt)" ]; then exit 1; fi
